WIDTH = 900
HEIGHT = 600
CHEK_PASSWORD_FROM_TABLE = "chek_password_form_table"
SIZE_OF_WINDOW = "900x600"
DEFAULT_FONT = "Halvetica"
GET_TABLE = "get_a_table"
REMOVE_ITEM_FROM_TABLE = "remove_item"
CIRCULATIONS_TABLE = "circulations_table"
EMPTY_SPACE = ""
COMPUTER_NAMES_TABLE = "computer_names_table"
TEACHERS_TABLE = "teachers_table"
PUPILS_TABLE = "pupils_table"
PASSWORD_TABLE = "password_table"
PRACTITIONERS_TABLE = "practitioners_table"
RED = "#1f6aa5"
GET_MAX = "get_max_column_of_the_table"
BACKGROUND_COLOR = ("gray84", "gray25")
MIDDLE = 0.5
